name: flutter_native_html_to_pdf
description: A pure Dart package to convert HTML to PDF bytes. Works on all platforms including web (JS & WASM) without native code.
version: 3.0.0
homepage: https://github.com/Pisey-Nguon
repository: https://github.com/Pisey-Nguon/flutter_native_html_to_pdf

environment:
  sdk: ">=3.5.0 <4.0.0"

platforms:
  android:
  ios:
  linux:
  macos:
  windows:
  web:

dependencies:
  pdf: ^3.11.3
  html: ^0.15.6
  http: ^1.6.0
  web: ^1.1.0

dev_dependencies:
  test: ^1.24.0
  lints: ^6.0.0
